# Generated by Django 5.1.3 on 2024-11-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='specifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
