# Generated by Django 5.1.3 on 2024-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_enquiry_messages_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
