# Generated by Django 5.1.3 on 2024-11-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_enquiry_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
